### ISSUE TITLE
Multiple letters propositions

### ISSUE THREAD

**Issue by Queng123** [cryck/sticker-composer#15]
Currently, we have 2 letters combinations for the given name.
If we take my username as example, there is:
- forward: `Q U EN G`
- backward: `Q U E NG`

It should be great to have a page selection, and on each page there will be each letters combinations.

For example (with my username and forward):
- Page 1: `Q U EN G`
- Page 2: `Q U E N G`

**Comment by cryck** [comment]
That would be a worthy feature as well. Will try to implement that in the upcoming days.

**Comment by Queng123** [comment]
Done in #21 (and fix in #24 )
