### ISSUE TITLE
Update file structure

### ISSUE THREAD

**Issue by cryck** [cryck/sticker-composer#19]
After cloning and contributing to the repo, I think it would be good to rearrange the files (for example have a folder front), in order to make the code more readable and more maintainable (there are starting to be a lot of lines in the files, which makes them more complex to understand)

_Originally posted by @Queng123 in https://github.com/cryck/sticker-composer/issues/18#issuecomment-1940978428_

**Comment by Queng123** [comment]
It could be great to have a contributing and some issue templates (also for features and bug reports)
