### ISSUE TITLE
[BUG] Sticker name is not fully visible on hover

### ISSUE THREAD

**Issue by rammba** [cryck/sticker-composer#29]
### Description

When we hover over sticker, it's name is not fully visible.

### Reproduction steps

```bash
1. Enter any word
2. Hover over sticker
```

### Screenshots
![image](https://github.com/cryck/sticker-composer/assets/40705899/553660e3-823e-4bd6-a53b-e97c5138041c)

**Comment by cryck** [comment]
Issue here is that the `sticker-wrapper` has the same `z-index` as the tooltip container as it is the same `sticker-wrapper` div. 

It could be solved when the only the currently hovered `sticker-wrapper` div would get a higher z-index. Tested it with `z-index: 20;`. I am not very well today though, so I can't work on that right now.

**Comment by cryck** [comment]
@Wilzzu thank you for taking this over!
