### ISSUE TITLE
Sticker playground

### ISSUE THREAD

**Issue by Lajtkek** [cryck/sticker-composer#5]
>Feature that would allow you to add stickers to "cart"
>You can now enter playground and try to move and rotate stickers to roughly see what the final craft would look like

**Comment by cryck** [comment]
@Lajtkek I am already working on implementing the playground, however I was struggling to find a good solution for adding the stickers there. Adding to "cart" is a really good option here. 

Appreciate the comment!

**Comment by cryck** [comment]
Update for this issue: The ground work for this has been done now by @Wilzzu. Will continue to work on the place on canvas functionality tomorrow.
